#log-level debug
log-level warn
log-size 64K
log-num 1

force-qtype-SOA 65

dnsmasq-lease-file /tmp/dnsmasq.leases
#conf-file /etc/storage/anti-ad-smartdns.conf
conf-file /etc/storage/smartdns_address.conf
conf-file /etc/storage/smartdns_blacklist-ip.conf
#conf-file /etc/storage/smartdns/bogus-nxdomain.china.smartdns.conf

serve-expired-ttl 345600
serve-expired-reply-ttl 1
serve-expired-prefetch-time 43200

rr-ttl-reply-max 600

speed-check-mode none
response-mode fastest-ip
edns-client-subnet 222.246.129.0/24
#edns-client-subnet 58.44.33.0/24
#edns-client-subnet 58.44.34.0/24
#
#
#########################Bootstrap#########################
#server 119.28.28.28 -group Bootstrap
server 119.29.29.29 -group Bootstrap -blacklist-ip
server 223.5.5.5    -group Bootstrap -blacklist-ip
#########################Bootstrap#########################
#
#
#China-HTTPS
server-https https://doh.pub/dns-query        -group china-https -blacklist-ip -exclude-default-group
server-https https://dns.alidns.com/dns-query -group china-https -blacklist-ip -exclude-default-group
#
#
#
#Oversea-HTTPS
server-https https://jp-kix.doh.sb/dns-query              -group oversea-https -blacklist-ip -exclude-default-group
server-https https://public.dns.iij.jp/dns-query          -group oversea-https -blacklist-ip -exclude-default-group
server-https https://dns-unfiltered.adguard.com/dns-query -group oversea-https -blacklist-ip -exclude-default-group

